version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
        - pip install pipenv==2018.6.25
        - pipenv run pip install pip==18.0
        - pipenv install
        - pipenv lock -r > requirements.txt
        - pip install -r requirements.txt -t  get_posts/build/
        - cp -R get_posts/app.py get_posts/build/
        - pipenv lock -r > requirements.txt
        - pip install -r requirements.txt -t  put_posts/build/
        - cp -R put_posts/app.py put_posts/build/
        - aws cloudformation package  --template-file template.yaml --output-template-file packaged.yaml   --s3-bucket build.adithyaneelavara.info
              # - command
      # - command
  post_build:
    commands:
       - aws cloudformation deploy --template-file ./packaged.yaml --capabilities CAPABILITY_IAM --stack-name serverlessblog
      # - command
artifacts:
  files:
    # ./packaged.yaml
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths