version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
        - pip install pipenv==2018.6.25
        - pipenv run pip install pip==18.0
        - pipenv install
        - ./build.sh
        - ./package.sh
      # - command
      # - command
  #post_build:
    #commands:
     #  - ./deploy.sh
      # - command
artifacts:
  files:
    - packaged.yaml
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths