AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    serverlessblog
    
    A Serverless Blog Application

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 5


Resources:

    GetBlogPostFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: get_posts/build/
            Handler: app.lambda_handler
            Runtime: python3.6
            Tracing: Active  # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
            Policies:
                - AmazonDynamoDBReadOnlyAccess
            Events:
                GetPosts:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /getPosts
                        Method: GET
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    DB_TABLE_NAME: blogposts
    PutBlogPostFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: put_posts/build/
            Handler: app.lambda_handler
            Runtime: python3.6
            Tracing: Active
            Role: arn:aws:iam::945746314187:role/LambdaBlogPublish
            Policies:
                - AmazonDynamoDBReadOnlyAccess
            Events:
                PutPosts:
                    Type: Api
                    Properties:
                        Path: /PutPosts
                        Method: POST
            
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    DB_TABLE_NAME: blogposts
Outputs:

    FirstFunction:
      Description: "GetBlogPostFunction ARN"
      Value: !GetAtt GetBlogPostFunction.Arn

